---
name: openQA - GitHub action example
# yamllint disable-line rule:truthy
on:
  # triggering on PRs is disabled here in favor of using the webhook-based approach
  # note: Use `pull_request_target` and not `pull_request` to enable it. Only then
  #       the workflow runs within the context of the main repository. This is
  #       necessary to allow accessing the secrets for API access.
  #pull_request_target:
  workflow_dispatch:
env:
  OPENQA_HOST: ${{ secrets.OPENQA_URL }}
  OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
  OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
  GH_REPO: ${github.event.pull_request.head.repo.full_name}}
  GH_REF: ${{github.event.pull_request.head.ref}}

jobs:
  trigger_and_monitor_openqa:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - uses: actions/checkout@v3
      - name: Trigger and monitor openQA test
        run: >
          openqa-cli schedule \
            --monitor \
            --host "${OPENQA_HOST:-https://openqa.opensuse.org}/" \
            --apikey "$OPENQA_API_KEY" --apisecret "$OPENQA_API_SECRET" \
            --param-file SCENARIO_DEFINITIONS_YAML=scenario-definitions.yaml \
            DISTRI=example VERSION=0 FLAVOR=DVD ARCH=x86_64 TEST=simple_boot \
            BUILD="$GH_REPO.git#$GH_REF" _GROUP_ID="0" \
            CASEDIR="$GITHUB_SERVER_URL/$GH_REPO.git#$GH_REF" \
            NEEDLES_DIR="%%CASEDIR%%/needles"
