---
name: openQA - GitHub action example
# yamllint disable-line rule:truthy
on:
  pull_request:
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
env:
  OPENQA_HOST: ${{ secrets.OPENQA_URL }}
  OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
  OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
  MOJO_CLIENT_DEBUG: 1

jobs:
  trigger_and_monitor_openqa:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers-tw/tumbleweed:client
    steps:
      - uses: actions/checkout@v3
      - name: Trigger and monitor openQA test
        run: >
          pwd &&
          ls -l &&
          openqa-cli --help &&
          openqa-cli schedule \
            --monitor \
            --host "${OPENQA_HOST:-https://openqa.opensuse.org}/" \
            --apibase "api/v1" \
            --apikey "$OPENQA_API_KEY" --apisecret "$OPENQA_API_SECRET" \
            --param-file SCENARIO_DEFINITIONS_YAML=scenario-definitions.yaml \
            DISTRI=example VERSION=0 FLAVOR=DVD ARCH=x86_64 TEST=simple_boot \
            BUILD="$GITHUB_REPOSITORY.git#$GITHUB_REF" GROUP_ID="0" \
            CASEDIR="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git#$GITHUB_REF" \
            NEEDLES_DIR="%%CASEDIR%%/needles"
